---
apiVersion: v1
kind: ReplicationController
metadata:
  name: myfirst-rc 
  labels:
    app: myapprc
    type: front-end
spec:
  template:
    metadata:
      name: mypod
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
        - name: mycont
          image: sarathindev/sandeepnginx:1.0
  replicas: 2

  


